# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d9324500-52e1-4655-9abc-dfe840a5c965";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/63be376e-7edb-4cc3-8992-3d9bc632b41b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
